### ISSUE TITLE
Code example is not accurate?

### ISSUE THREAD

**Issue by melezhik** [Garland-g/Universal-errno#2]
Hi! I just copied and pasted a code example from the doc, and executed in RP. And got this error:

```
Could not find symbol '&INET' in 'AF'
  in block <unit> at code.rakuplay-1605929899.raku line 8
  in block <unit> at -e line 1
```

Maybe it's just absence of usage some other module?

Full log is here - https://rakudist.raku.org/sparky/report/RakuPlay-2/1412

**Comment by Garland-g** [comment]
That is correct. I have pushed an update to the example code so that it explicitly uses the required modules for that example.
